quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=mysql123
quarkus.datasource.jdbc.url=jdbc:mysql://mysql-examen:3306/cliente_db

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.http.port=8082
quarkus.http.host=0.0.0.0