quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=mysql123
quarkus.datasource.jdbc.url=jdbc:mysql://mysql-examen:3306/productos_db

quarkus.http.port=8080
quarkus.http.host=0.0.0.0