quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=mysql123
quarkus.datasource.jdbc.url=jdbc:mysql://mysql-examen:3306/ventas_db

quarkus.http.port=8083
quarkus.http.host=0.0.0.0

producto-api/mp-rest/url=http://ms-producto:8080
cliente-api/mp-rest/url=http://ms-cliente:8082

quarkus.fault-tolerance.enabled=true