CREATE DATABASE IF NOT EXISTS db_usuarios;
CREATE DATABASE IF NOT EXISTS db_libros;
CREATE DATABASE IF NOT EXISTS db_prestamos;
CREATE DATABASE IF NOT EXISTS db_reservas;
CREATE DATABASE IF NOT EXISTS db_multas;
CREATE DATABASE IF NOT EXISTS db_notificaciones;
