services:
  mysql-biblioteca:
    image: mysql:8.0
    container_name: biblioteca-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
    ports:
      - "3310:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - mysql-biblioteca-data:/var/lib/mysql

  config-server:
    build: ./config-server
    container_name: biblioteca-config-server
    ports:
      - "8888:8888"
    volumes:
      - ./central-config:/config

  eureka-server:
    build: ./eureka-server
    container_name: biblioteca-eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  ms-lib-usuarios:
    build: ./ms-lib-usuarios
    container_name: biblioteca-ms-lib-usuarios
    ports:
      - "8081:8081"
    depends_on:
      - mysql-biblioteca
      - config-server
      - eureka-server

  ms-lib-libros:
    build: ./ms-lib-libros
    container_name: biblioteca-ms-lib-libros
    ports:
      - "8082:8082"
    depends_on:
      - mysql-biblioteca
      - config-server
      - eureka-server

  ms-lib-prestamos:
    build: ./ms-lib-prestamos
    container_name: biblioteca-ms-lib-prestamos
    ports:
      - "8083:8083"
    depends_on:
      - mysql-biblioteca
      - config-server
      - eureka-server
      - ms-lib-usuarios
      - ms-lib-libros
      - ms-lib-multas
      - ms-lib-notificaciones

  ms-lib-reservas:
    build: ./ms-lib-reservas
    container_name: biblioteca-ms-lib-reservas
    ports:
      - "8084:8084"
    depends_on:
      - mysql-biblioteca
      - config-server
      - eureka-server
      - ms-lib-usuarios
      - ms-lib-libros
      - ms-lib-notificaciones

  ms-lib-multas:
    build: ./ms-lib-multas
    container_name: biblioteca-ms-lib-multas
    ports:
      - "8085:8085"
    depends_on:
      - mysql-biblioteca
      - config-server
      - eureka-server
      - ms-lib-notificaciones

  ms-lib-notificaciones:
    build: ./ms-lib-notificaciones
    container_name: biblioteca-ms-lib-notificaciones
    ports:
      - "8086:8086"
    depends_on:
      - mysql-biblioteca
      - config-server
      - eureka-server

  api-gateway:
    build: ./api.gateway
    container_name: biblioteca-api-gateway
    ports:
      - "8040:8030"
    depends_on:
      - eureka-server
      - ms-lib-usuarios
      - ms-lib-libros
      - ms-lib-prestamos
      - ms-lib-reservas
      - ms-lib-multas
      - ms-lib-notificaciones

volumes:
  mysql-biblioteca-data:
