quarkus.config.locations=file:/app/central-config/common.properties,file:/app/central-config/ms-ventas.properties

quarkus.application.name=ms-ventas
quarkus.consul-config.enabled=false
quarkus.http.host=0.0.0.0