quarkus.config.locations=file:/app/central-config/common.properties,file:/app/central-config/ms-producto.properties

quarkus.application.name=ms-producto
quarkus.consul-config.enabled=false
quarkus.http.host=0.0.0.0